name: apiverve_companynamegenerator
description: Company Name Generator is a simple tool for generating company names. It returns a list of company names based on the specified keyword.
version: 1.1.14
homepage: https://apiverve.com/marketplace/companynamegenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/companynamegenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
